# Credenciais para envio de e-mail
[email_credentials]
username = "theolimaff@gmail.com"
password = "mjpe cxxj ffvp bukc"

# E-mail que receberá as notificações
[recipient]
email = "theolimaff@gmail.com"